[0m02:05:08.108022 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000023E428956D0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000023E45330DC0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000023E453305E0>]}


============================== 02:05:08.120296 | f6de9b94-a51c-47fa-bb25-d10acbbb71b8 ==============================
[0m02:05:08.120296 [info ] [MainThread]: Running with dbt=1.8.7
[0m02:05:08.121250 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'version_check': 'True', 'profiles_dir': 'C:\\Users\\Sakib\\.dbt', 'log_path': 'logs', 'fail_fast': 'False', 'debug': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'empty': 'None', 'log_format': 'default', 'static_parser': 'True', 'invocation_command': 'dbt init', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'target_path': 'None', 'introspect': 'True', 'send_anonymous_usage_stats': 'True'}
[0m02:05:08.145270 [warn ] [MainThread]: [ConfigFolderDirectory]: Unable to parse logging event dictionary. Failed to parse dir field: expected string or bytes-like object.. Dictionary: {'dir': WindowsPath('C:/Users/Sakib/.dbt')}
[0m02:05:08.146272 [info ] [MainThread]: Creating dbt configuration folder at 
[0m02:05:27.266005 [debug] [MainThread]: Starter project path: d:\dbt_project\dbt_env\lib\site-packages\dbt\include\starter_project
[0m02:05:27.293999 [info ] [MainThread]: 
Your new dbt project "test_project" was created!

For more information on how to configure the profiles.yml file,
please consult the dbt documentation here:

  https://docs.getdbt.com/docs/configure-your-profile

One more thing:

Need help? Don't hesitate to reach out to us via GitHub issues or on Slack:

  https://community.getdbt.com/

Happy modeling!

[0m02:05:27.295995 [info ] [MainThread]: Setting up your profile.
[0m02:05:36.487493 [error] [MainThread]: Encountered an error:
'type' object is not subscriptable
[0m02:05:36.535514 [error] [MainThread]: Traceback (most recent call last):
  File "d:\dbt_project\dbt_env\lib\site-packages\dbt\cli\requires.py", line 138, in wrapper
    result, success = func(*args, **kwargs)
  File "d:\dbt_project\dbt_env\lib\site-packages\dbt\cli\requires.py", line 101, in wrapper
    return func(*args, **kwargs)
  File "d:\dbt_project\dbt_env\lib\site-packages\dbt\cli\main.py", line 470, in init
    results = task.run()
  File "d:\dbt_project\dbt_env\lib\site-packages\dbt\task\init.py", line 347, in run
    self.setup_profile(profile_name)
  File "d:\dbt_project\dbt_env\lib\site-packages\dbt\task\init.py", line 263, in setup_profile
    self.create_profile_from_target(adapter, profile_name=profile_name)
  File "d:\dbt_project\dbt_env\lib\site-packages\dbt\task\init.py", line 173, in create_profile_from_target
    load_plugin(adapter)
  File "d:\dbt_project\dbt_env\lib\site-packages\dbt\adapters\factory.py", line 239, in load_plugin
    return FACTORY.load_plugin(name)
  File "d:\dbt_project\dbt_env\lib\site-packages\dbt\adapters\factory.py", line 68, in load_plugin
    mod: Any = import_module("." + name, "dbt.adapters")
  File "D:\Softwares\Miniconda\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "d:\dbt_project\dbt_env\lib\site-packages\dbt\adapters\duckdb\__init__.py", line 4, in <module>
    from dbt.adapters.duckdb.impl import DuckDBAdapter
  File "d:\dbt_project\dbt_env\lib\site-packages\dbt\adapters\duckdb\impl.py", line 40, in <module>
    class DuckDBAdapter(SQLAdapter):
  File "d:\dbt_project\dbt_env\lib\site-packages\dbt\adapters\duckdb\impl.py", line 55, in DuckDBAdapter
    _temp_schema_model_uuid: dict[str, str] = defaultdict(lambda: str(uuid4()).split("-")[-1])
TypeError: 'type' object is not subscriptable

[0m02:05:36.540490 [debug] [MainThread]: Command `dbt init` failed at 02:05:36.540490 after 28.48 seconds
[0m02:05:36.541489 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000023E428956D0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000023E42762CA0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000023E42762820>]}
[0m02:05:36.541489 [debug] [MainThread]: Flushing usage events
[0m04:08:33.543423 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000256B0490B80>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000256B229F850>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000256B229F940>]}


============================== 04:08:33.549423 | c075afda-14d2-482e-9b54-54bf50de288b ==============================
[0m04:08:33.549423 [info ] [MainThread]: Running with dbt=1.9.2
[0m04:08:33.550425 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': 'C:\\Users\\Sakib\\.dbt', 'fail_fast': 'False', 'warn_error': 'None', 'log_path': 'logs', 'version_check': 'True', 'debug': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'empty': 'None', 'log_format': 'default', 'static_parser': 'True', 'introspect': 'True', 'invocation_command': 'dbt init', 'target_path': 'None', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'send_anonymous_usage_stats': 'True'}
[0m04:08:42.034112 [info ] [MainThread]: A project called test_project already exists here.
[0m04:08:42.035135 [debug] [MainThread]: Command `dbt init` succeeded at 04:08:42.035135 after 8.54 seconds
[0m04:08:42.036159 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000256B0490B80>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000256B229F7F0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000256B22E4640>]}
[0m04:08:42.036159 [debug] [MainThread]: Flushing usage events
[0m04:08:43.321700 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m04:09:35.592531 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001D9F5170AC0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001D9F6F7D8E0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001D9F6F7D9D0>]}


============================== 04:09:35.596549 | c4f9757d-fd9a-492e-8972-ef0d90fa6940 ==============================
[0m04:09:35.596549 [info ] [MainThread]: Running with dbt=1.9.2
[0m04:09:35.598539 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': 'C:\\Users\\Sakib\\.dbt', 'version_check': 'True', 'warn_error': 'None', 'log_path': 'logs', 'fail_fast': 'False', 'debug': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'empty': 'None', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'invocation_command': 'dbt init', 'log_format': 'default', 'introspect': 'True', 'target_path': 'None', 'static_parser': 'True', 'send_anonymous_usage_stats': 'True'}
[0m04:09:40.859225 [debug] [MainThread]: Starter project path: d:\dbt_project\dbt_env\lib\site-packages\dbt\include\starter_project
[0m04:09:40.911033 [info ] [MainThread]: 
Your new dbt project "test_project" was created!

For more information on how to configure the profiles.yml file,
please consult the dbt documentation here:

  https://docs.getdbt.com/docs/configure-your-profile

One more thing:

Need help? Don't hesitate to reach out to us via GitHub issues or on Slack:

  https://community.getdbt.com/

Happy modeling!

[0m04:09:40.914327 [info ] [MainThread]: Setting up your profile.
[0m04:09:44.655940 [debug] [MainThread]: Traceback (most recent call last):
  File "d:\dbt_project\dbt_env\lib\site-packages\dbt\adapters\factory.py", line 68, in load_plugin
    mod: Any = import_module("." + name, "dbt.adapters")
  File "D:\Softwares\Miniconda\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 790, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "d:\dbt_project\dbt_env\lib\site-packages\dbt\adapters\duckdb\__init__.py", line 2, in <module>
    from dbt.adapters.duckdb.connections import DuckDBConnectionManager  # noqa
  File "d:\dbt_project\dbt_env\lib\site-packages\dbt\adapters\duckdb\connections.py", line 11, in <module>
    from . import environments
  File "d:\dbt_project\dbt_env\lib\site-packages\dbt\adapters\duckdb\environments\__init__.py", line 11, in <module>
    import duckdb
  File "d:\dbt_project\dbt_env\lib\site-packages\duckdb\__init__.py", line 4, in <module>
    import duckdb.functional as functional
  File "d:\dbt_project\dbt_env\lib\site-packages\duckdb\functional\__init__.py", line 1, in <module>
    from duckdb.duckdb.functional import (
ModuleNotFoundError: No module named 'duckdb.duckdb'

[0m04:09:44.656940 [error] [MainThread]: Encountered an error:
No module named 'duckdb.duckdb'
[0m04:09:44.658783 [error] [MainThread]: Traceback (most recent call last):
  File "d:\dbt_project\dbt_env\lib\site-packages\dbt\cli\requires.py", line 153, in wrapper
    result, success = func(*args, **kwargs)
  File "d:\dbt_project\dbt_env\lib\site-packages\dbt\cli\requires.py", line 103, in wrapper
    return func(*args, **kwargs)
  File "d:\dbt_project\dbt_env\lib\site-packages\dbt\cli\main.py", line 477, in init
    results = task.run()
  File "d:\dbt_project\dbt_env\lib\site-packages\dbt\task\init.py", line 346, in run
    self.setup_profile(profile_name)
  File "d:\dbt_project\dbt_env\lib\site-packages\dbt\task\init.py", line 262, in setup_profile
    self.create_profile_from_target(adapter, profile_name=profile_name)
  File "d:\dbt_project\dbt_env\lib\site-packages\dbt\task\init.py", line 172, in create_profile_from_target
    load_plugin(adapter)
  File "d:\dbt_project\dbt_env\lib\site-packages\dbt\adapters\factory.py", line 239, in load_plugin
    return FACTORY.load_plugin(name)
  File "d:\dbt_project\dbt_env\lib\site-packages\dbt\adapters\factory.py", line 68, in load_plugin
    mod: Any = import_module("." + name, "dbt.adapters")
  File "D:\Softwares\Miniconda\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 790, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "d:\dbt_project\dbt_env\lib\site-packages\dbt\adapters\duckdb\__init__.py", line 2, in <module>
    from dbt.adapters.duckdb.connections import DuckDBConnectionManager  # noqa
  File "d:\dbt_project\dbt_env\lib\site-packages\dbt\adapters\duckdb\connections.py", line 11, in <module>
    from . import environments
  File "d:\dbt_project\dbt_env\lib\site-packages\dbt\adapters\duckdb\environments\__init__.py", line 11, in <module>
    import duckdb
  File "d:\dbt_project\dbt_env\lib\site-packages\duckdb\__init__.py", line 4, in <module>
    import duckdb.functional as functional
  File "d:\dbt_project\dbt_env\lib\site-packages\duckdb\functional\__init__.py", line 1, in <module>
    from duckdb.duckdb.functional import (
ModuleNotFoundError: No module named 'duckdb.duckdb'

[0m04:09:44.664782 [debug] [MainThread]: Command `dbt init` failed at 04:09:44.664782 after 9.13 seconds
[0m04:09:44.664782 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001D9F5170AC0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001D9F7010C10>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001D9F4430100>]}
[0m04:09:44.665780 [debug] [MainThread]: Flushing usage events
[0m04:09:46.072486 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m04:38:29.967781 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001F9643F0BB0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001F9661FF7F0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001F9661FF8E0>]}


============================== 04:38:29.972778 | e8eaf22a-145c-4047-8c2a-e252d41c85ed ==============================
[0m04:38:29.972778 [info ] [MainThread]: Running with dbt=1.9.2
[0m04:38:29.974137 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': 'C:\\Users\\Sakib\\.dbt', 'debug': 'False', 'version_check': 'True', 'log_path': 'logs', 'fail_fast': 'False', 'warn_error': 'None', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'empty': 'None', 'log_format': 'default', 'introspect': 'True', 'invocation_command': 'dbt init', 'static_parser': 'True', 'target_path': 'None', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'send_anonymous_usage_stats': 'True'}
[0m04:38:33.990370 [debug] [MainThread]: Starter project path: d:\dbt_project\dbt_env\lib\site-packages\dbt\include\starter_project
[0m04:38:34.015369 [info ] [MainThread]: 
Your new dbt project "test" was created!

For more information on how to configure the profiles.yml file,
please consult the dbt documentation here:

  https://docs.getdbt.com/docs/configure-your-profile

One more thing:

Need help? Don't hesitate to reach out to us via GitHub issues or on Slack:

  https://community.getdbt.com/

Happy modeling!

[0m04:38:34.017369 [info ] [MainThread]: Setting up your profile.
[0m04:38:37.414866 [info ] [MainThread]: Profile test written to C:\Users\Sakib\.dbt\profiles.yml using target's sample configuration. Once updated, you'll be able to start developing with dbt.
[0m04:38:37.416883 [debug] [MainThread]: Command `dbt init` succeeded at 04:38:37.415875 after 7.51 seconds
[0m04:38:37.416883 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001F9643F0BB0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001F960047C40>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001F966290CD0>]}
[0m04:38:37.416883 [debug] [MainThread]: Flushing usage events
[0m04:38:38.803822 [debug] [MainThread]: An error was encountered while trying to flush usage events
